### ISSUE TITLE
[S1 - PBI3] Pemesanan

### ISSUE THREAD

**Issue by ryansupriadi1** [SI-RPL-2021/SI4203---Repair.inc#12]
Sebagai user, saya ingin dapat memesan jasa sesuai dengan yang diinginkan, sehingga saya tidak perlu khawatir lagi 
dengan permasalahan yang saya alami

**Comment by ryansupriadi1** [comment]
https://repair--inc.000webhostapp.com/

Activity Diagram Pemesanan
![pemesanan](https://user-images.githubusercontent.com/71846567/116274310-bfdbd200-a7ac-11eb-8c18-2ba6c7d71b63.png)
Note: task yang diberi warna merah adalah PBI Pemesanan

**Comment by yusufyop** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/71863166/116282093-9030c800-a7b4-11eb-9586-39d8901ddd5c.png)
revisi mockup pemesanan dan pembayaran

**Comment by yusufyop** [comment]
![Desktop - 3](https://user-images.githubusercontent.com/71863166/119292746-2f918f80-bc7b-11eb-9d61-b5819ce55da3.png)
mockup pemesanan
