### ISSUE TITLE
[S2 - PBI10]  Tracking

### ISSUE THREAD

**Issue by annisanrkhrn** [SI-RPL-2021/SI4203---Repair.inc#14]
Sebagai User, saya ingin terdapat layanan tracking status pemesanan, sehingga saya dapat memantau progress secara transparan

**Comment by yusufyop** [comment]
https://repair--inc.000webhostapp.com/

Activity Diagram Tracking POV: Customer
![tracking (2)](https://user-images.githubusercontent.com/71846567/116286866-ed7b4800-a7b9-11eb-8612-ea580aede1a9.png)
Note: Task berwarna merah adalah PBI Tracking

Mockup
Berikut merupakan tampilan tracking dari point of view customer, terdapat tracking details berisi progress yang akan masuk ke dalam field history.
![Tracking fix](https://user-images.githubusercontent.com/71846567/119295301-b9902700-bc80-11eb-80e8-ecedc0bd19f4.png)
