### ISSUE TITLE
[S3 - PBI11] About us

### ISSUE THREAD

**Issue by annisanrkhrn** [SI-RPL-2021/SI4203---Repair.inc#15]
Sebagai Admin, saya ingin adanya fitur about us pada landing page, sehingga saya dapat memberikan informasi singkat mengenai website saya

**Comment by anggitakhaerunisa** [comment]
https://repair--inc.000webhostapp.com/

Mockup About Us pada Landing Page
![Landing Page   Homepage](https://user-images.githubusercontent.com/71863166/111113224-07f3bc00-8594-11eb-9c55-937d1bd82972.png)

Activity Diagram About Us
![about us](https://user-images.githubusercontent.com/71846567/119300075-5905e780-bc8a-11eb-90be-a96b42177fd1.png)
