### ISSUE TITLE
[S2 - PBI9] Create Akun Mitra

### ISSUE THREAD

**Issue by ryansupriadi1** [SI-RPL-2021/SI4203---Repair.inc#24]
Sebagai admin saya bisa membuat akun mitra yang mendaftar di website kami, sehingga mitra dapat menggunakan website Repair.inc untuk melakukan penawaran jasa yang dimiliki

**Comment by anggitakhaerunisa** [comment]
https://repair--inc.000webhostapp.com/

Activity Diagram Mengelola Akun Mitra
![create mitra](https://user-images.githubusercontent.com/71846567/116278828-121ef200-a7b1-11eb-8d53-0b2ca1a58664.png)

Mockup
Berikut merupakan menu Mitra, berisi list mitra yang sudah terdaftar
![ADMIN (Create Mitra)](https://user-images.githubusercontent.com/71846567/116280300-b9e8ef80-a7b2-11eb-9a2c-651bd76f680a.png)
Jika admin ingin menambahkan mitra baru, maka ketika diklik button +Mitra Baru, akan muncul modals untuk mengisi data mitra
![ADMIN (Create Mitra2)](https://user-images.githubusercontent.com/71846567/116280304-bb1a1c80-a7b2-11eb-9e02-f0edd6d56f07.png)
