### ISSUE TITLE
[S1 - PBI2] Request Order

### ISSUE THREAD

**Issue by ryansupriadi1** [SI-RPL-2021/SI4203---Repair.inc#8]
Sebagai Mitra Penyedia Jasa, saya ingin dapat menerima ataupun menolak transaksi yang masuk sehingga saya dapat melakukan pekerjaan dengan fleksibel

**Comment by ryansupriadi1** [comment]
https://repair--inc.000webhostapp.com/

Activity Diagram Request Order POV: Mitra Penyedia Jasa
![Request Order vpd](https://user-images.githubusercontent.com/71846567/116271138-e8ae9800-a7a9-11eb-813c-28f353736589.png)
Mockup Request Order POV: Mitra Penyedia Jasa
![image](https://user-images.githubusercontent.com/71914247/111113349-396c8780-8594-11eb-943c-3814f5f8376e.png)
Setelah diapprove, maka akan muncul detail pemesanan seperti berikut: 
![After Pembayaran (Detail Pemesanan) (2)](https://user-images.githubusercontent.com/71846567/116337326-26d8a580-a804-11eb-83ab-e29fb9bc0e70.png)

**Comment by anggitakhaerunisa** [comment]
Activity Diagram Request Order, POV: Mitra Penyedia Jasa
![Request Order vpd](https://user-images.githubusercontent.com/71846567/116270729-8bb2e200-a7a9-11eb-906d-fc7973b3fb64.png)
