### ISSUE TITLE
[S1 - PBI5] Payment

### ISSUE THREAD

**Issue by anggitakhaerunisa** [SI-RPL-2021/SI4203---Repair.inc#9]
Sebagai User, saya ingin  melakukan pembayaran sehingga transaksi dapat berjalan dengan baik

**Comment by anggitakhaerunisa** [comment]
https://repair--inc.000webhostapp.com/

Activity Diagram Payment
![pembayaran](https://user-images.githubusercontent.com/71846567/116277972-37f7c700-a7b0-11eb-8535-d6d5283bd543.png)
Note: Task berwarna merah adalah PBI Payment

**Comment by yusufyop** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/71863166/116282093-9030c800-a7b4-11eb-9586-39d8901ddd5c.png)
revisi mockup pemesanan dan pembayaran
